Document the interpreter metadata on content in the Partner v3 API
kivra/developer.kivra.com pull request #124
Opened 2023-08-10 09:34 UTC by kivra-fabber

2023-08-22 13:33 UTC, kivra-ponern requested changes
Nitpicks :hamster:

2023-08-22 13:33 UTC, kivra-ponern commented on swagger.yml
> +        A given content can contain multiple files ("parts"), to download one, pass the `part` query parameter.
```suggestion
        A given content can contain multiple files ("parts"). Fetching of such parts is done by passing the `part` query parameter.
```
Not sure "download" is the word to use.

2023-08-22 13:33 UTC, kivra-ponern commented on swagger.yml
> +
Consider joining these two paragraphs.
```suggestion
```

2023-08-22 13:33 UTC, kivra-ponern commented on swagger.yml
> +          nullable: true
And just to verify it's `null` and not empty array `[]`?

2023-08-22 13:33 UTC, kivra-ponern commented on swagger.yml
> +          example: "Faktura: tusen rulltårtor"
Would be nicer to keep the examples in English.
```suggestion
          example: "Invoice: a thousand Swiss rolls"
```
:laughing:

2023-08-22 13:33 UTC, kivra-ponern commented on swagger.yml
>            example: Takplåt
English please.

2023-08-22 13:33 UTC, kivra-ponern commented on swagger.yml
> +        [Get specific content](#tag/Partner-API-v3/operation/Get%20content) endpoint.
```suggestion
        Note that more content metadata is available via the
        [Get specific content](#tag/Partner-API-v3/operation/Get%20content) endpoint.
```
Disclaimer reads weirdly imo.

2023-08-22 14:13 UTC, kivra-fabber commented on swagger.yml
> +          nullable: true
Correct, if not available from the sender, or the interpreter, it will be null.

2023-08-23 13:00 UTC, kivra-ponern approved these changes

2023-08-23 13:35 UTC, merged