K4B-2937 Update PAPI docs
kivra/developer.kivra.com pull request #182
Opened 2024-10-24 07:52 UTC by maxno-kivra

This fixes two issues with the documentation for PAPI. First off, when updating the labels of a content you must nest them under `labels`. Secondly, the interpreter has been deprecated and this marks all related fields as such and removes a paragraph about it.

---

This also does some cleanup. I had a hard time navigating the swagger file with its >5000 lines. Fortunately there's support for splitting OpenAPI docs into multiple files using `$ref`, which this does. This also meant changing the cloud build deployment, and I didn't want to keep piling copy-pasted one-liners to that YAML file. So instead I refactored those into a proper script. This could be further improved but I'll leave that for a rainy day.

2024-10-24 13:54 UTC, kivra-fabber requested changes
Please separate the reorganisation to a separate PR. I cannot review the fixes to the labels and the interpreter in a diff like this.

2024-10-24 14:28 UTC, maxno-kivra commented
The split is now in #185.

2024-10-28 13:18 UTC, kivra-fabber approved these changes
Nice!

2024-10-28 13:19 UTC, kivra-fabber commented on swagger.yml
> +      Endpoints for partner access to company mailboxes.
Good catch 👍

2024-10-28 13:19 UTC, merged

2024-10-28 13:20 UTC, kivra-fabber commented on swagger.yml
> +                Café AB,SE556000475501
also good catch ⭐